package io.apex.parser.f1.enums

enum Nationality(val value: Int) {
  case USA extends Nationality(1)
  case ARGENTINA extends Nationality(2)
  case AUSTRALIA extends Nationality(3)
  case AUSTRIA extends Nationality(4)
  case AZERBAIJAN extends Nationality(5)
  case BAHRAIN extends Nationality(6)
  case BELGIUM extends Nationality(7)
  case BOLIVIA extends Nationality(8)
  case BRAZIL extends Nationality(9)
  case UK extends Nationality(10)
  case BULGARIA extends Nationality(11)
  case CAMEROON extends Nationality(12)
  case CANADA extends Nationality(13)
  case CHILE extends Nationality(14)
  case CHINA extends Nationality(15)
  case COLOMBIA extends Nationality(16)
  case COSTA_RICA extends Nationality(17)
  case CROATIA extends Nationality(18)
  case CYPRUS extends Nationality(19)
  case CZECHIA extends Nationality(20)
  case DANMARK extends Nationality(21)
  case NETHERLANDS extends Nationality(22)
  case ECUADOR extends Nationality(23)
  case ENGLAND extends Nationality(24)
  case EMIRATES extends Nationality(25)
  case ESTONIA extends Nationality(26)
  case FINLAND extends Nationality(27)
  case FRANCE extends Nationality(28)
  case GERMANY extends Nationality(29)
  case GHANA extends Nationality(30)
  case GREECE extends Nationality(31)
  case GUATEMALA extends Nationality(32)
  case HONDURAS extends Nationality(33)
  case HONK_KONG extends Nationality(34)
  case HUNGARY extends Nationality(35)
  case ICELAND extends Nationality(36)
  case INDIA extends Nationality(37)
  case INDONESIA extends Nationality(38)
  case IRELAND extends Nationality(39)
  case ISRAEL extends Nationality(40)
  case ITALY extends Nationality(41)
  case JAMAICA extends Nationality(42)
  case JAPAN extends Nationality(43)
  case JORDAN extends Nationality(44)
  case KUWAIT extends Nationality(45)
  case LATVIA extends Nationality(46)
  case LEBANON extends Nationality(47)
  case LITHUANIA extends Nationality(48)
  case LUXEMBOURG extends Nationality(49)
  case MALAYSIA extends Nationality(50)
  case MALTA extends Nationality(51)
  case MEXICO extends Nationality(52)
  case MONACO extends Nationality(53)
  case NEW_ZEALAND extends Nationality(54)
  case NICARAGUA extends Nationality(55)
  case NORTH_KOREA extends Nationality(56)
  case NORTHERN_IRELAND extends Nationality(57)
  case NORWAY extends Nationality(58)
  case OMAN extends Nationality(59)
  case PAKISTAN extends Nationality(60)
  case PANAMA extends Nationality(61)
  case PARAGUAY extends Nationality(62)
  case PERU extends Nationality(63)
  case POLAND extends Nationality(64)
  case PORTUGAL extends Nationality(65)
  case QATAR extends Nationality(66)
  case ROMANIA extends Nationality(67)
  case RUSSIA extends Nationality(68)
  case EL_SALVADOR extends Nationality(69)
  case SAUDI_ARABIA extends Nationality(70)
  case SCOTLAND extends Nationality(71)
  case SERBIA extends Nationality(72)
  case SINGAPORE extends Nationality(73)
  case SLOVAKIA extends Nationality(74)
  case SLOVENIA extends Nationality(75)
  case SOUTH_KOREA extends Nationality(76)
  case SOUTH_AFRICA extends Nationality(77)
  case SPAIN extends Nationality(78)
  case SWEDEN extends Nationality(79)
  case SWITZERLAND extends Nationality(80)
  case THAILAND extends Nationality(81)
  case TURKEY extends Nationality(82)
  case URUGUAY extends Nationality(83)
  case UKRAINE extends Nationality(84)
  case VENEZUELA extends Nationality(85)
  case WALES extends Nationality(86)
  case BARBADOS extends Nationality(87)
  case VIETNAM extends Nationality(88)
}

object Nationality {
  def valueOf(value: Int): Option[Nationality] =
    Nationality.values.find(_.value == value)
}
